name: consumer-security-pipeline
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  dockerfile-lint:
    name: Lint Dockerfile with hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: catalogue-web/Dockerfile
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: inventory-api/Dockerfile

  python-sast:
    name: Check python code with bandit
    needs: dockerfile-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install bandit==1.7.9
      - name: Run bandit
        run: bandit -r . -ll

  security-scan:
    needs: python-sast
    uses: devopsDanW/gh_actions_shared/.github/workflows/security-scan.yml@v1.1.0
    with:
      severity: "CRITICAL,HIGH"


  sbom:
    needs: dockerfile-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t inventory-api:ci inventory-api/
      - run: docker build -t catalogue-web:ci catalogue-web/
      - name: install trivy
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.74.0
      - name: generate sbom for inventory-api
        run: trivy image --format spdx-json --output inventory-api-sbom.json inventory-api:ci
      - name: generate sbom for catalogue-web
        run: trivy image --format spdx-json --output catalogue-web-sbom.json catalogue-web:ci
      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: |
            inventory-api-sbom.json
            catalogue-web-sbom.json

